(import java.util.HashMap)
(deftemplate person "Person" (slot name (default Unnamed))(slot age (default 0))(slot gender))
(deffunction eq (?arg1 ?arg2)(printout t "Comparing " ?arg1 " and " ?arg2 crlf)(if (<> ?arg1 ?arg2) then (return FALSE)) else (return TRUE))
(deftemplate device "Device" (slot name)(slot device_type)(slot manufacturer)(slot OS)(slot display_resolution (default 0))(slot storage)(slot camera)(multislot connectivity)(multislot input_output)(slot battery (default 0))(slot price (default 0)))
(set-reset-globals nil)
(defglobal ?*global_price* = 0)
(defglobal ?*global_type* = undefined)
(defrule is_price "Checks price of device" (device {price < ?*global_price*})=>(printout t "WE found device type " ?*global_price* crlf))
(defrule is_type "Checks type of device" (device {device_type == ?*global_type*}(name ?name))=>(bind ?result (new java.util.HashMap))(?result put "name" ?name)(add ?result))